<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>markdown</string>
		<string>mdown</string>
		<string>markdn</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Markdown (GitHub)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?:^|\G)(#{1,6})\s*(?=[\S[^#]])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading..markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.section.markdown</string>
			<key>end</key>
			<string>\s*(#{1,6})?$\n?</string>
			<key>name</key>
			<string>markup.heading.${1/(#)(#)?(#)?(#)?(#)?(#)?/${6:?6:${5:?5:${4:?4:${3:?3:${2:?2:1}}}}}/}.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```AppleScript</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.applescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.applescript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.applescript.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.applescript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Bash</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.shell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.shell</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.shell.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```C++</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.c++</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.c++</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.c++.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```CSS</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.css</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.css.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```C</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.c</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.c.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```HTML</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.html.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```JSON</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.json</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.json</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.json.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Javascript</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.js</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.js.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Java</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.java.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```LaTeX</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.tex.latex.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Markdown</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.html.markdown.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Mathematica</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.mathematica</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.mathematica</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.mathematica.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.mathematica</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Matlab</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.matlab</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.matlab</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.matlab.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.matlab</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Objective-C\+\+</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.objc++</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.objc++</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.objc++.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.objc++</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Objective-C</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.objc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.objc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.objc.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.objc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Perl</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.perl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.perl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.perl.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```PHP</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.php</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.php</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.html.php.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.php</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```PostScript</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.postscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.postscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.postscript.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.postscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Python</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.python</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.python.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Ruby</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.ruby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.ruby</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ruby.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```R</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.r</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.r</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.r.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Scala</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.scala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.scala</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.scala.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```SQL</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.sql</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.sql</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.sql.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```Swift</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.swift</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.swift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.swift.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.swift</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```TeX</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.tex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.tex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.tex.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>```XML</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>```</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.xml.embedded.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.markdown</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.github</string>
	<key>uuid</key>
	<string>B3E1EB57-A62F-409B-BC1F-9BAE31114A98</string>
</dict>
</plist>
